### ISSUE TITLE
Flask-based Backend server for completing the pipeline

### ISSUE THREAD

**Issue by duaraghav8** [duaraghav8/Corque#2]
Need a flask-based backend server that receives a POST request from client along with single image of the class and initiates the facial recognition engine, passing on the image.
The REST server is also responsible for collecting the output from the engine (list of Student SAP IDs present in class) and sends back to client as API response (JSON)
@devershichandra27

**Comment by devershichandra27** [comment]
On it!

**Comment by devershichandra27** [comment]
Made a flask server, which gives you a JSON list of SAP IDs of present students, from the uploaded image.

**Comment by duaraghav8** [comment]
#4
